name: open_pattern_icons
description: "Open Pattern icons for generating knitting charts"
version: 0.1.0
homepage: https://github.com/open-pattern-format/opaf-pattern-icons

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
  - icons/
